name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "finalizando login"
    - name: Docker build image
      run: |
        docker build -t fgbonta/docker-graphql:0.0.2 .
        docker image tag fgbonta/docker-graphql:0.0.2 fgbonta/docker-graphql:latest
    - name: Docker push image
      run: |
        docker push fgbonta/docker-graphql:0.0.2
        docker push fgbonta/docker-graphql:latest
        
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
